name: Send PR Data on Close

on:
  pull_request:
    types: [closed]

jobs:
  send-pr-data:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Obtener comentarios del PR
        id: comments
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            // Devolver como string multilínea
            return comments.map(c => `${c.user.login}: ${c.body}`).join("\n");

      - name: Guardar en Notion
        run: |
          jq -n \
            --arg db "26aa14b248a0802eae81ea4a45fa820a" \
            --arg pr_number "${{ github.event.pull_request.number }}" \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg merged_by "${{ github.event.pull_request.merged_by.login }}" \
            --arg comments "${{ steps.comments.outputs.result }}" \
            '{
              parent: { database_id: $db },
              properties: {
                "PR Number": { number: ($pr_number | tonumber) },
                "Title": { title: [{ text: { content: $title } }] },
                "Merged By": { rich_text: [{ text: { content: $merged_by } }] },
                "Comments": { rich_text: [{ text: { content: $comments } }] }
              }
            }' \
          | curl -s -X POST "https://api.notion.com/v1/pages" \
              -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
              -H "Content-Type: application/json" \
              -H "Notion-Version: 2022-06-28" \
              -d @-
