name: Send PR Data on Close

on:
  pull_request:

jobs:
  send-pr-data:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener commits del PR
        id: commits
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            return commits.map(c => `- ${c.commit.message}`).join("\n");

      - name: Ver PR body
        run: echo "${{ github.event.pull_request.body }}"

