name: Send PR Data on Close

on:
  pull_request:
    types: [closed]

jobs:
  send-pr-data:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Obtener comentarios del PR
        id: comments
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            return {
              comments: comments.map(c => `${c.user.login}: ${c.body}`).join(" | ")
            }

      - name: Guardar en Notion
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d '{
              "parent": { "database_id": "26aa14b248a0802eae81ea4a45fa820a" },
              "properties": {
                "PR Number": { "number": ${{ github.event.pull_request.number }} },
                "Title": { "title": [{ "text": { "content": "${{ github.event.pull_request.title }}" }}] },
                "Merged By": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.merged_by.login }}" }}] },
                "Comments": { "rich_text": [{ "text": { "content": "${{ steps.comments.outputs.result }}" }}] }
              }
            }'
