name: Send PR Data on Close

on:
  pull_request:
    types: [closed]

jobs:
  send-pr-data:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Obtener commits del PR
        id: commits
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            return commits.map(c => `- ${c.commit.message}`).join("\n");

      - name: Obtener summary de CodeRabbit
        id: summary
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            const summary = comments.find(c =>
              c.body && c.body.trim().startsWith("Summary by CodeRabbit")
            );

            return summary ? summary.body : "No se encontró resumen";

      - name: Guardar en Notion
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d '{
              "parent": { "database_id": "26aa14b2-48a0-802e-ae81-ea4a45fa820a" },
              "properties": {
                "PR Number": { "number": '${{ github.event.pull_request.number }}' },
                "Title": { "title": [{ "text": { "content": "${{ github.event.pull_request.title }}" }}] },
                "Merged By": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.merged_by.login }}" }}] },
                "Merged at": { "date": { "start": "${{ github.event.pull_request.merged_at }}" } },
                "Comments": { "rich_text": [{ "text": { "content": ${{ toJSON(steps.commits.outputs.result) }} }}] },
                "Summary": { "rich_text": [{ "text": { "content": ${{ toJSON(steps.summary.outputs.result) }} }}] }
              }
            }'
